#!/usr/bin/env python
"""Rewrite the README's sourcing-coverage block from the emitted dataset.

The README quotes a "% of nodes sourced or verified" figure. So that number is a
real count of the shipped data and never drifts from it, this tool reads the
programmatic tally the generator emits (``public/data/meta.json`` ->
``provenance_stats``, see ``generate_data.py`` ``_provenance_stats``) and rewrites
the block between the two marker comments in ``README.md``::

    <!-- SOURCING_STATS:START ... -->
    ... generated headline + per-kind table ...
    <!-- SOURCING_STATS:END -->

It also keeps the header's proof-first one-liner in sync, if the README wraps that
figure in a second pair of inline markers::

    <!-- SOURCED_HEADLINE:START --><b>NN% of the M knowledge nodes ...</b><!-- SOURCED_HEADLINE:END -->

so the headline and the block below can never drift (the header markers are optional;
a README without them is left untouched).

It likewise regenerates the table of reference works grading is checked against, from
``meta.source_corpora``, between an optional third pair of markers::

    <!-- SOURCES_TABLE:START ... -->
    | Source | Field | Grades here | ...
    <!-- SOURCES_TABLE:END -->

It only ever touches the text between those markers (everything else in the README
is hand-written), is idempotent, and is stdlib-only like the other data tools. Run
it after regenerating the data (``python tools/generate_data.py``) whenever the
sourcing changes::

    python tools/update_readme_stats.py            # rewrite the block in place
    python tools/update_readme_stats.py --check     # exit 1 if it would change (CI)

Built with the help of Claude Code.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
META = REPO / "public" / "data" / "meta.json"
# The English README is canonical; the French translation carries the same generated
# blocks (English data labels; anglicisms are fine) so its numbers never drift. Each
# is spliced only where its markers are present, and a missing file is skipped.
READMES = [REPO / "README.md", REPO / "README.fr.md"]

START = "<!-- SOURCING_STATS:START (generated by tools/update_readme_stats.py; do not edit by hand) -->"
END = "<!-- SOURCING_STATS:END -->"

# The README header also leads with the headline figure (proof-first). These inline
# markers let this tool keep that one number in sync with the block below, so the
# two never drift; they are optional (a README without them is left untouched).
HEAD_START = "<!-- SOURCED_HEADLINE:START -->"
HEAD_END = "<!-- SOURCED_HEADLINE:END -->"

# The README also carries a table of the reference works grading is checked against.
# It is generated from meta.source_corpora so it lists exactly the corpora the dataset
# cites and never drifts. Optional (spliced only if the markers are present).
SRC_START = "<!-- SOURCES_TABLE:START (generated by tools/update_readme_stats.py; do not edit by hand) -->"
SRC_END = "<!-- SOURCES_TABLE:END -->"

# Editorial framing per corpus: the field it is a standard reference in, and the node
# kinds it grades here. Keyed by the meta.source_corpora id. The factual bits (title,
# link) come from the data; only this framing is copy. A cited corpus missing here
# fails the run loudly, so a newly added source can never ship undescribed.
CORPUS_DESC = {
    "stahl":           ("Clinical psychopharmacology", "Drug bindings, nomenclature, class"),
    "kandel":          ("Neuroscience (standard textbook)", "Neuron pathways, region anatomy"),
    "stahl_essential": ("Psychopharmacology (mechanisms)", "Receptor & target mechanism"),
    "carlat":          ("Clinical psychopharmacology", "Drug bindings (cross-check)"),
    "nieuwenhuys":     ("Neuroanatomy (CNS atlas)", "Region anatomy, connectivity"),
    "gtopdb":          ("Molecular pharmacology (IUPHAR/BPS database)", "Receptor & target expression regions"),
    "pdsp_ki":         ("Receptor binding pharmacology", "Drug binding affinities (Ki)"),
    "allen_ahba":      ("Brain transcriptome atlas (microarray)", "Receptor & target expression regions"),
    "wikipedia_pharm": ("Encyclopedia (pharmacodynamics tables)", "Drug binding affinities (Ki)"),
    "wikipedia_fr":    ("Encyclopedia (French, article prose)", "Drug brand names (European / French)"),
    "gtopdb_ki":       ("Molecular pharmacology (IUPHAR/BPS database)", "Drug binding affinities (Ki) and direction"),
    "gtopdb_class":    ("Molecular pharmacology (IUPHAR/BPS database)", "Receptor & target mechanism class, receptor sign"),
}

# Per-node-kind display labels for the README table (English; the README is English).
# Keys mirror meta.provenance_stats.by_kind; an unknown kind would simply title-case.
KIND_LABELS = {
    "drug_bindings": "Drug target bindings",
    "drug_nbn": "Drug nomenclature (NbN)",
    "drug_brands": "Drug brand names",
    "drug_categories": "Drug class",
    "drug_half_life": "Drug half-life (T½)",
    "drug_enzymes": "Drug metabolising enzymes",
    "drug_metabolites": "Drug active metabolites",
    "drug_metabolite_enzyme": "Metabolite-forming enzymes",
    "drug_metabolite_bindings": "Drug metabolite bindings",
    "projections": "Neuron pathways",
    "circuits": "Functional circuits",
    "projection_groups": "Projection groups",
    "receptors": "Receptor system/family",
    "receptor_class": "Receptor mechanism class",
    "receptor_sign": "Receptor sign (excit./inhib.)",
    "receptor_synaptic": "Receptor pre/postsynaptic site",
    "receptor_locations": "Receptor expression regions",
    "targets": "Target classifications",
    "target_polarity": "Target tone polarity",
    "target_locations": "Target expression regions",
    "structures": "Brain-region anatomy",
    "references": "Wikipedia reference links",
}


def render_headline(stats: dict) -> str:
    """The proof-first one-liner in the README header (between the SOURCED_HEADLINE
    markers), kept identical to the block headline below so the two never diverge."""
    a = stats["nodes"]
    # <b> not ** : this line sits inside a GitHub [!IMPORTANT] admonition, where
    # markdown bold (**) does not render but the inline HTML tag does.
    return (f"<b>{a['pct_backed']}% of the {a['total']} knowledge nodes "
            f"are sourced or verified</b>")


def render_sources_table(corpora: dict) -> str:
    """Build the 'sources used for grading' table from meta.source_corpora, so it
    lists exactly the corpora the dataset cites and never drifts. Each source links
    out when it has a public URL (the copyrighted books do not)."""
    missing = [cid for cid in corpora if cid not in CORPUS_DESC]
    if missing:
        raise SystemExit(
            f"error: source corpora {missing} have no CORPUS_DESC entry in "
            f"tools/update_readme_stats.py; describe them so the README table is complete")
    lines = [
        SRC_START,
        "",
        "Every `~` and `✓` grade is checked against one of the sources below. Each is a "
        "standard, widely cited reference in its field, not a casual web page:",
        "",
        "| Source | Field | Grades here |",
        "| --- | --- | --- |",
    ]
    for cid, c in corpora.items():
        field, grades = CORPUS_DESC[cid]
        ref = c["ref"].replace("|", "\\|")
        url = c.get("url", "") or ""
        name = f"[{ref}]({url})" if url.startswith(("http://", "https://")) else ref
        lines.append(f"| {name} | {field} | {grades} |")
    lines += ["", SRC_END]
    return "\n".join(lines)


def splice_inline(text: str, start: str, end: str, inner: str) -> str:
    """Replace the text between two inline markers, keeping the markers. Left
    unchanged if either marker is absent (so a README not using them still works)."""
    if start not in text or end not in text:
        return text
    pre, rest = text.split(start, 1)
    _, post = rest.split(end, 1)
    return pre + start + inner + end + post


BAR_WIDTH = 26  # cells in the README progress bars (monospace, so they align)


def render_block(stats: dict) -> str:
    """Build the markdown between the markers from meta.provenance_stats: a headline
    sentence + a monospace progress-bar chart (one bar per node kind, best-covered
    first), rendered in a fenced code block so the bars align when GitHub renders it."""
    a = stats["nodes"]
    # Rows are sorted best-covered first (by the exact backed/total ratio, so the
    # displayed % reads top-to-bottom monotonically even when two rows round to the
    # same figure); ties break by the larger denominator, then the KIND_LABELS order
    # for a stable, deterministic chart.
    rows = []
    for order, (kind, label) in enumerate(KIND_LABELS.items()):
        c = stats["by_kind"].get(kind)
        if not c or not c["total"]:
            continue
        # ``uncertain`` is backed: the claim rests on a quote-checked document, the
        # badge only flags that the sentence does not attribute it (see
        # tools/data_generators/quotes/uncertainty.py).
        backed = c["verified"] + c.get("uncertain", 0) + c["sourced"]
        rows.append((backed, c["total"], order, label))
    rows.sort(key=lambda r: (-(r[0] / r[1]), -r[1], r[2]))

    label_w = max((len(label) for _b, _t, _o, label in rows), default=0)
    count_w = max((len(f"{b}/{t}") for b, t, _o, _l in rows), default=0)
    chart = []
    for backed, total, _order, label in rows:
        pct = round(100 * backed / total)
        filled = round(BAR_WIDTH * backed / total)
        bar = "█" * filled + "░" * (BAR_WIDTH - filled)  # full block / light shade
        count = f"{backed}/{total}"
        chart.append(f"{label:<{label_w}}  {bar}  {pct:>3}%  {count:>{count_w}}")

    lines = [
        START,
        "",
        f"**{a['pct_backed']}% of the {a['total']} knowledge nodes in the dataset "
        f"are sourced or verified.** A node is any sourceable datum (a region, a "
        f"pathway, a receptor, a drug binding, ...). This is a programmatic count "
        f"(`tools/update_readme_stats.py`, from the emitted data), not hand-typed:",
        "",
        "```",
        *chart,
        "```",
    ]
    # Measured-affinity (PDSP Ki) coverage: a SEPARATE honesty line, not part of the %
    # above. A binding backed by a book quote with no Ki is still sourced, so "no Ki" is
    # not "unsourced"; this states how much of the corpus carries a *measured* affinity
    # and how many drugs never had one looked up, so a quote-only corpus can't read as
    # exhaustively measured. Omitted on an older dataset that predates the field.
    ki = stats.get("ki_coverage")
    if ki and ki.get("bindings_total"):
        lines += [
            "",
            f"Separately, **measured binding affinity (PDSP Ki) covers "
            f"{ki['pct_bindings_with_ki']}% of the {ki['bindings_total']} drug "
            f"bindings**; {ki['drugs_without_ki']} of {ki['drugs_total']} drugs carry "
            f"no Ki on any binding (sourced by book quote only, or not yet sourced). A "
            f"Ki is a measured value, not a grade: this tracks where one was never "
            f"looked up, complementing the sourcing figure above.",
        ]
    # The "uncertain" badge: nodes whose quote is confirmed present but does not
    # attribute the claim. They stay *backed* above (a real document does exist), so
    # this is the line that keeps that from reading as a clean bill of health.
    uncertain = a.get("uncertain", 0)
    if uncertain:
        lines += [
            "",
            f"Of those, **{uncertain} carry an `uncertain` badge**: the quote is "
            f"confirmed present in the source, but the sentence states a general rule "
            f"without naming the drug, so the attribution is an inference. The badge's "
            f"tooltip lists the reasons to doubt it, each with its own source.",
        ]
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block is out of date (write nothing)")
    args = ap.parse_args()

    meta = json.loads(META.read_text(encoding="utf-8"))
    stats = meta.get("provenance_stats")
    if not stats:
        print("error: meta.provenance_stats missing; run generate_data.py first",
              file=sys.stderr)
        return 2
    corpora = meta.get("source_corpora") or {}

    def rewrite(text: str) -> str:
        """Splice the generated blocks (coverage bars, headline, sources table) into
        one README's text; each splice is a no-op if its markers are absent."""
        pre, rest = text.split(START, 1)
        _, post = rest.split(END, 1)
        out = pre + render_block(stats) + post
        out = splice_inline(out, HEAD_START, HEAD_END, render_headline(stats))
        if SRC_START in out and SRC_END in out:
            s_pre, s_rest = out.split(SRC_START, 1)
            _, s_post = s_rest.split(SRC_END, 1)
            out = s_pre + render_sources_table(corpora) + s_post
        return out

    rc = 0
    for readme in READMES:
        if not readme.exists():
            continue  # the French translation is optional
        text = readme.read_text(encoding="utf-8")
        if START not in text or END not in text:
            print(f"error: markers not found in {readme.name}; add a block:\n"
                  f"  {START}\n  {END}", file=sys.stderr)
            return 2
        new_text = rewrite(text)
        if new_text == text:
            print(f"{readme.name} sourcing block already up to date.")
            continue
        if args.check:
            print(f"{readme.name} sourcing block is OUT OF DATE "
                  f"(run tools/update_readme_stats.py)", file=sys.stderr)
            rc = 1
            continue
        readme.write_text(new_text, encoding="utf-8")
        print(f"updated the sourcing block in {readme.name} "
              f"({stats['nodes']['pct_backed']}% of "
              f"{stats['nodes']['total']} nodes).")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
