#!/usr/bin/env python
"""Rewrite the README's sourcing-coverage block from the emitted dataset.

The README quotes a "% of claims sourced or verified" figure. So that number is a
real count of the shipped data and never drifts from it, this tool reads the
programmatic tally the generator emits (``public/data/meta.json`` ->
``provenance_stats``, see ``generate_data.py`` ``_provenance_stats``) and rewrites
the block between the two marker comments in ``README.md``::

    <!-- SOURCING_STATS:START ... -->
    ... generated headline + per-kind table ...
    <!-- SOURCING_STATS:END -->

It only ever touches the text between those markers (everything else in the README
is hand-written), is idempotent, and is stdlib-only like the other data tools. Run
it after regenerating the data (``python tools/generate_data.py``) whenever the
sourcing changes::

    python tools/update_readme_stats.py            # rewrite the block in place
    python tools/update_readme_stats.py --check     # exit 1 if it would change (CI)

Built with the help of Claude Code.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
META = REPO / "public" / "data" / "meta.json"
README = REPO / "README.md"

START = "<!-- SOURCING_STATS:START (generated by tools/update_readme_stats.py; do not edit by hand) -->"
END = "<!-- SOURCING_STATS:END -->"

# Per-kind display labels for the README table (English; the README is English).
# Keys mirror meta.provenance_stats.by_kind; an unknown kind would simply title-case.
KIND_LABELS = {
    "drug_bindings": "Drug target bindings",
    "drug_nbn": "Drug nomenclature (NbN)",
    "drug_descriptions": "Drug descriptions",
    "projections": "Neuron pathways",
    "references": "Wikipedia reference links",
}


def render_block(stats: dict) -> str:
    """Build the markdown between the markers from meta.provenance_stats."""
    a = stats["assertions"]
    lines = [
        START,
        "",
        f"**{a['pct_backed']}% of the {a['total']} factual claims in the dataset "
        f"are sourced or verified.** This is a programmatic count "
        f"(`tools/update_readme_stats.py`, from the emitted data), not hand-typed:",
        "",
        "| Claim kind | Sourced or verified |",
        "| --- | --- |",
    ]
    for kind, label in KIND_LABELS.items():
        c = stats["by_kind"].get(kind)
        if not c or not c["total"]:
            continue
        backed = c["verified"] + c["sourced"]
        pct = round(100 * backed / c["total"])
        lines.append(f"| {label} | {backed} / {c['total']} ({pct}%) |")
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block is out of date (write nothing)")
    args = ap.parse_args()

    meta = json.loads(META.read_text(encoding="utf-8"))
    stats = meta.get("provenance_stats")
    if not stats:
        print("error: meta.provenance_stats missing; run generate_data.py first",
              file=sys.stderr)
        return 2

    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"error: markers not found in {README.name}; add a block:\n"
              f"  {START}\n  {END}", file=sys.stderr)
        return 2

    pre, rest = text.split(START, 1)
    _, post = rest.split(END, 1)
    new_text = pre + render_block(stats) + post

    if new_text == text:
        print("README sourcing block already up to date.")
        return 0
    if args.check:
        print("README sourcing block is OUT OF DATE (run tools/update_readme_stats.py)",
              file=sys.stderr)
        return 1
    README.write_text(new_text, encoding="utf-8")
    print(f"updated the sourcing block in {README.name} "
          f"({stats['assertions']['pct_backed']}% of "
          f"{stats['assertions']['total']} claims).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
