#!/usr/bin/env python
"""Rewrite the README's sourcing-coverage block from the emitted dataset.

The README quotes a "% of nodes sourced or verified" figure. So that number is a
real count of the shipped data and never drifts from it, this tool reads the
programmatic tally the generator emits (``public/data/meta.json`` ->
``provenance_stats``, see ``generate_data.py`` ``_provenance_stats``) and rewrites
the block between the two marker comments in ``README.md``::

    <!-- SOURCING_STATS:START ... -->
    ... generated headline + per-kind table ...
    <!-- SOURCING_STATS:END -->

It also keeps the header's proof-first one-liner in sync, if the README wraps that
figure in a second pair of inline markers::

    <!-- SOURCED_HEADLINE:START --><b>NN% of the M knowledge nodes ...</b><!-- SOURCED_HEADLINE:END -->

so the headline and the block below can never drift (the header markers are optional;
a README without them is left untouched).

It likewise regenerates the table of reference works grading is checked against, from
``meta.source_corpora``, between an optional third pair of markers::

    <!-- SOURCES_TABLE:START ... -->
    | Source | Field | Grades here | ...
    <!-- SOURCES_TABLE:END -->

It only ever touches the text between those markers (everything else in the README
is hand-written), is idempotent, and is stdlib-only like the other data tools. Run
it after regenerating the data (``python tools/generate_data.py``) whenever the
sourcing changes::

    python tools/update_readme_stats.py            # rewrite the block in place
    python tools/update_readme_stats.py --check     # exit 1 if it would change (CI)

Built with the help of Claude Code.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
META = REPO / "public" / "data" / "meta.json"
README = REPO / "README.md"

START = "<!-- SOURCING_STATS:START (generated by tools/update_readme_stats.py; do not edit by hand) -->"
END = "<!-- SOURCING_STATS:END -->"

# The README header also leads with the headline figure (proof-first). These inline
# markers let this tool keep that one number in sync with the block below, so the
# two never drift; they are optional (a README without them is left untouched).
HEAD_START = "<!-- SOURCED_HEADLINE:START -->"
HEAD_END = "<!-- SOURCED_HEADLINE:END -->"

# The README also carries a table of the reference works grading is checked against.
# It is generated from meta.source_corpora so it lists exactly the corpora the dataset
# cites and never drifts. Optional (spliced only if the markers are present).
SRC_START = "<!-- SOURCES_TABLE:START (generated by tools/update_readme_stats.py; do not edit by hand) -->"
SRC_END = "<!-- SOURCES_TABLE:END -->"

# Editorial framing per corpus: the field it is a standard reference in, and the node
# kinds it grades here. Keyed by the meta.source_corpora id. The factual bits (title,
# link) come from the data; only this framing is copy. A cited corpus missing here
# fails the run loudly, so a newly added source can never ship undescribed.
CORPUS_DESC = {
    "stahl":           ("Clinical psychopharmacology", "Drug bindings, nomenclature, class"),
    "kandel":          ("Neuroscience (standard textbook)", "Neuron pathways, region anatomy"),
    "stahl_essential": ("Psychopharmacology (mechanisms)", "Receptor & target mechanism"),
    "carlat":          ("Clinical psychopharmacology", "Drug bindings (cross-check)"),
    "nieuwenhuys":     ("Neuroanatomy (CNS atlas)", "Region anatomy, connectivity"),
    "gtopdb":          ("Molecular pharmacology (IUPHAR/BPS database)", "Receptor & target expression regions"),
    "pdsp_ki":         ("Receptor binding pharmacology", "Drug binding affinities (Ki)"),
}

# Per-node-kind display labels for the README table (English; the README is English).
# Keys mirror meta.provenance_stats.by_kind; an unknown kind would simply title-case.
KIND_LABELS = {
    "drug_bindings": "Drug target bindings",
    "drug_nbn": "Drug nomenclature (NbN)",
    "drug_categories": "Drug class",
    "projections": "Neuron pathways",
    "circuits": "Functional circuits",
    "projection_groups": "Projection groups",
    "receptors": "Receptor classifications",
    "receptor_locations": "Receptor expression regions",
    "targets": "Target classifications",
    "target_locations": "Target expression regions",
    "structures": "Brain-region anatomy",
    "references": "Wikipedia reference links",
}


def render_headline(stats: dict) -> str:
    """The proof-first one-liner in the README header (between the SOURCED_HEADLINE
    markers), kept identical to the block headline below so the two never diverge."""
    a = stats["nodes"]
    # <b> not ** : this line sits inside a GitHub [!IMPORTANT] admonition, where
    # markdown bold (**) does not render but the inline HTML tag does.
    return (f"<b>{a['pct_backed']}% of the {a['total']} knowledge nodes "
            f"are sourced or verified</b>")


def render_sources_table(corpora: dict) -> str:
    """Build the 'sources used for grading' table from meta.source_corpora, so it
    lists exactly the corpora the dataset cites and never drifts. Each source links
    out when it has a public URL (the copyrighted books do not)."""
    missing = [cid for cid in corpora if cid not in CORPUS_DESC]
    if missing:
        raise SystemExit(
            f"error: source corpora {missing} have no CORPUS_DESC entry in "
            f"tools/update_readme_stats.py; describe them so the README table is complete")
    lines = [
        SRC_START,
        "",
        "Every `~` and `✓` grade is checked against one of the sources below. Each is a "
        "standard, widely cited reference in its field, not a casual web page:",
        "",
        "| Source | Field | Grades here |",
        "| --- | --- | --- |",
    ]
    for cid, c in corpora.items():
        field, grades = CORPUS_DESC[cid]
        ref = c["ref"].replace("|", "\\|")
        url = c.get("url", "") or ""
        name = f"[{ref}]({url})" if url.startswith(("http://", "https://")) else ref
        lines.append(f"| {name} | {field} | {grades} |")
    lines += ["", SRC_END]
    return "\n".join(lines)


def splice_inline(text: str, start: str, end: str, inner: str) -> str:
    """Replace the text between two inline markers, keeping the markers. Left
    unchanged if either marker is absent (so a README not using them still works)."""
    if start not in text or end not in text:
        return text
    pre, rest = text.split(start, 1)
    _, post = rest.split(end, 1)
    return pre + start + inner + end + post


def render_block(stats: dict) -> str:
    """Build the markdown between the markers from meta.provenance_stats."""
    a = stats["nodes"]
    lines = [
        START,
        "",
        f"**{a['pct_backed']}% of the {a['total']} knowledge nodes in the dataset "
        f"are sourced or verified.** A node is any sourceable datum (a region, a "
        f"pathway, a receptor, a drug binding, ...). This is a programmatic count "
        f"(`tools/update_readme_stats.py`, from the emitted data), not hand-typed:",
        "",
        "| Node kind | Sourced or verified |",
        "| --- | --- |",
    ]
    # Rows are sorted best-covered first (by the exact backed/total ratio, so the
    # displayed % reads top-to-bottom monotonically even when two rows round to the
    # same figure); ties break by the larger denominator, then the KIND_LABELS order
    # for a stable, deterministic table.
    rows = []
    for order, (kind, label) in enumerate(KIND_LABELS.items()):
        c = stats["by_kind"].get(kind)
        if not c or not c["total"]:
            continue
        backed = c["verified"] + c["sourced"]
        rows.append((backed, c["total"], order, label))
    rows.sort(key=lambda r: (-(r[0] / r[1]), -r[1], r[2]))
    for backed, total, _order, label in rows:
        pct = round(100 * backed / total)
        lines.append(f"| {label} | {backed} / {total} ({pct}%) |")
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block is out of date (write nothing)")
    args = ap.parse_args()

    meta = json.loads(META.read_text(encoding="utf-8"))
    stats = meta.get("provenance_stats")
    if not stats:
        print("error: meta.provenance_stats missing; run generate_data.py first",
              file=sys.stderr)
        return 2

    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"error: markers not found in {README.name}; add a block:\n"
              f"  {START}\n  {END}", file=sys.stderr)
        return 2

    pre, rest = text.split(START, 1)
    _, post = rest.split(END, 1)
    new_text = pre + render_block(stats) + post
    # Keep the header's proof-first figure in sync too (no-op if the markers are absent).
    new_text = splice_inline(new_text, HEAD_START, HEAD_END, render_headline(stats))
    # Keep the sources table in sync from meta.source_corpora (no-op if markers absent).
    if SRC_START in new_text and SRC_END in new_text:
        corpora = meta.get("source_corpora") or {}
        s_pre, s_rest = new_text.split(SRC_START, 1)
        _, s_post = s_rest.split(SRC_END, 1)
        new_text = s_pre + render_sources_table(corpora) + s_post

    if new_text == text:
        print("README sourcing block already up to date.")
        return 0
    if args.check:
        print("README sourcing block is OUT OF DATE (run tools/update_readme_stats.py)",
              file=sys.stderr)
        return 1
    README.write_text(new_text, encoding="utf-8")
    print(f"updated the sourcing block in {README.name} "
          f"({stats['nodes']['pct_backed']}% of "
          f"{stats['nodes']['total']} nodes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
